name: shad_swe_design
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.11
  - mypy=0.910
  - flake8=3.9.2
  - pytest=6.2.5
  - pylint=2.12.2
  - Pillow=8.1.2
  - PySimpleGUI=4.59.0
  - pip:
      - pynput==1.7.6
