name: CI
on: [ push, workflow_dispatch ]
env:
  # Increase this value to reset cache if etc/example-environment.yml has not changed
  CACHE_NUMBER: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: cache-testing-venv
        uses: actions/cache@v2
        with:
          path: ${{ github.event.repository.name }}/testing_venv/
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
      - name: conda-environment-installation
        run: make .testing-venv
  test:
   runs-on: ubuntu-latest
   needs: [ build ]
   steps:
     - uses: actions/checkout@v2
     - name: cache-testing-venv
       uses: actions/cache@v2
       with:
         path: ${{ github.event.repository.name }}/testing_venv/
         key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
     - name: run-tests
       run: make test
     - name: run-linters
       run: make lint
